version: '3.8'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-blog
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
    volumes:
      # 持久化数据目录
      - ./data:/app/server/data
      # 日志目录
      - ./logs:/app/logs
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  blog-network:
    driver: bridge

volumes:
  blog-data:

